### ISSUE TITLE
 LINUX server version needed

### ISSUE THREAD

**Issue by xizhesun** [lizhao007/DeepBSA#1]
Dear developers,

DeepBSA has a good GUI, meanwhile it relys on WINDOWS system. As running DeepBSA need a lot CPU and memory, it runs very slowly on the PC. I think it will be much faster on LINUX server. Is there an LINUX server version which support multiple CPUs?

Best regards,
Xizhe

**Comment by lizhao007** [comment]
Thanks for using DeepBSA and suggesting it, we have been developing the Linux version of the software and it has been released now, here is the download link: http://zeasystemsbio.hzau.edu.cn/tools.html.

**Comment by xizhesun** [comment]
well done, cheers 👍
