### ISSUE TITLE
tuple index out of range

### ISSUE THREAD

**Issue by HorticLee** [lizhao007/DeepBSA#10]
Hello, when I use DeepBSA_linux_v1.4 with parameter:
**python main.py --i high_low_pool.snp.vcf --m SNP --p 1 --p1 10 --p2 1 --p3 1 --s LOWESS --w 0 --t 0**

There was an error:
**Traceback (most recent call last):
  File "main.py", line 95, in <module>
    main(args)
  File "main.py", line 73, in main
    args.w, args.t, save_path)
  File "/DeepBSA_linux_v1.4/bin/functions/Statistic_Methods.py", line 515, in __init__
    self.num_pools = np.array(self.data[0]).shape[1]
IndexError: tuple index out of range**

**When I test the data in demo, it works but faild with my data. Was there any problem with my data, there was 18 chr, when I divided them into two parts, 1 vcf with 10 chr and another with 8 chr, it works with the 2 file.**

Thank you.
[high_low_pool.snp.vcf.gz](https://github.com/lizhao007/DeepBSA/files/11414986/high_low_pool.snp.vcf.gz)

**Comment by HorticLee** [comment]
Solved it, I rename the chr name to number 8 and it works.

**Comment by HorticLee** [comment]
maybe the chr number is too large ?
**when I divided them into two parts, 1 vcf with 10 chr and another file with 8 chr, it works with the 2 file seperately**, but when I combine all the 18 chr together, it failed.

**Comment by lizhao007** [comment]
Sorry for the late reply, the above problem is a bug in Linux version, which will be fixed later. You can try the Windows version, which works normally. I tested it and got good results on chromosome 8.

**Comment by HorticLee** [comment]
> Sorry for the late reply, the above problem is a bug in Linux version, which will be fixed later. You can try the Windows version, which works normally. I tested it and got good results on chromosome 8.

okay, thank you very much.
