### ISSUE TITLE
window版本的DeepBSA使用总是闪退

### ISSUE THREAD

**Issue by DengHAU** [lizhao007/DeepBSA#12]
李博士，你好，

请问win版的deepbsa在使用的时候总是计算中途闪退会是什么原因导致的，因为系统没有安装CUDA的模块Linux版本的不能使用DL算法，win版本的就一直闪退。是否有解决办法？

**Comment by lizhao007** [comment]
请问您按说明安装了R吗？我刚试了试，我这边用还是没问题的

**Comment by DengHAU** [comment]
是的李博，我按照PDF安装了R，前几次能用，最近一直都不能成功运行，总是在计算途中闪退，多数是在计算到第五或者第六条染色体时突然闪退了。

**Comment by lizhao007** [comment]
好的，有时候是电脑内存或者系统环境原因，有两个方法可以先简单排查下。一个是试试减少数据量，比如只跑2-3条染色体看看；另一个是试试将Windows Rate参数（默认0）调整到0.1。

**Comment by DengHAU** [comment]
多谢李博，我试一试！

**Comment by lizhao007** [comment]
最近发现另一个可能的原因，当数据点较少时，预处理可能进一步使单条染色体上的SNP被过滤完，从而导致闪退，可以测试下闪退的数据不进行预处理的结果。
