### ISSUE TITLE
linux版本运行demo数据总是报错

### ISSUE THREAD

**Issue by leehg165** [lizhao007/DeepBSA#13]
李老师，您好
我在服务器上安装了linux的1.4版本，尝试用test.csv数据来运行，却总是报错，麻烦看下是怎么回事？
输入命令如下：
`python main.py --i /public/home/zzuaga07/tools/DeepBSA_linux_v1.4/demo/test.csv --p 0 `
提示下面错误：
`Traceback (most recent call last):

  File "main.py", line 95, in <module>
    main(args)

  File "main.py", line 71, in main
    dl = Statistic(args.m, freq_data_path, ref_data_path, mut_data_path, 

  File "/public/home/zzuaga07/tools/DeepBSA_linux_v1.4/bin/functions/Statistic_Methods.py", line 510, in __init__
    self.data = np.load(self.data_path, allow_pickle=True)

  File "/public/home/zzuaga07/anaconda3/envs/deepbsa/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))

FileNotFoundError: [Errno 2] No such file or directory: '/public/home/zzuaga07/tools/DeepBSA_linux_v1.4/bin/NoPretreatment/test_freq.npy'`

**Comment by lizhao007** [comment]
&nbsp; &nbsp; 你好，我这边刚试了下，运行正常，如下：




&nbsp; &nbsp; 你看看你是在bin/目录下运行的吗，以及有没有生成NoPretreatment目录及内容。另外可以试试windows版本，操作更简单。


祝好
李昭


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lizhao007/DeepBSA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月4日(星期五) 下午5:08
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[lizhao007/DeepBSA] linux版本运行demo数据总是报错 (Issue #13)





 
李老师，您好
 我在服务器上安装了linux的1.4版本，尝试用test.csv数据来运行，却总是报错，麻烦看下是怎么回事？
 输入命令如下：
 python main.py --i /public/home/zzuaga07/tools/DeepBSA_linux_v1.4/demo/test.csv --p 0 
 提示下面错误：
 `Traceback (most recent call last):
 
File "main.py", line 95, in 
 main(args)
 
File "main.py", line 71, in main
 dl = Statistic(args.m, freq_data_path, ref_data_path, mut_data_path,
 
File "/public/home/zzuaga07/tools/DeepBSA_linux_v1.4/bin/functions/Statistic_Methods.py", line 510, in init
 self.data = np.load(self.data_path, allow_pickle=True)
 
File "/public/home/zzuaga07/anaconda3/envs/deepbsa/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
 fid = stack.enter_context(open(os_fspath(file), "rb"))
 
FileNotFoundError: [Errno 2] No such file or directory: '/public/home/zzuaga07/tools/DeepBSA_linux_v1.4/bin/NoPretreatment/test_freq.npy'`

**Comment by leehg165** [comment]
是在bin/目录下运行的，生成了NoPretreatment目录，目录下有test_freq.npy但是为空文件
