### ISSUE TITLE
模型输入

### ISSUE THREAD

**Issue by ctrlCV666** [lizhao007/DeepBSA#2]
你好，我想咨询一下论文中U-Net的输入（Figure1.C）
1. SNP的Pos信息也输入模型了吗？
2.  SNP-Index通常是滑动窗口计算的频率，这里用的是单SNP频率吗？
3.  另外负样本**frequency fluctuates around 0.5 in pools**具体参数是多少呢？

**Comment by lizhao007** [comment]
你好，欢迎使用DeepBSA:
1、SNP的Pos信息没有输入模型，计算出值后再加上的POS信息作为输出；
2、这里所有方法都是计算的单SNP的算法值，画拟合线时才用Smooth方法进行拟合；
3、正负样本都是根据频率变化图（figure 1B）标记的，没有具体参数。
