### ISSUE TITLE
在linux下使用发生报错：IndexError：list index out of range

### ISSUE THREAD

**Issue by wsweishang** [lizhao007/DeepBSA#3]
你好，在linux下使用发生报错，麻烦您看下哈：
<img width="945" alt="56D0871A-0590-4d57-9327-1C63CC534BCD" src="https://user-images.githubusercontent.com/35129244/228101462-db767f91-8e0e-4fe3-8078-c1576eecb58f.png">

这是我使用的命令行和输入文件：
python3 ~/app/bioinfo/dna/DeepBSA_linux_v1.4/bin/main.py  --i deepBSA.csv

[deepBSA.csv](https://github.com/lizhao007/DeepBSA/files/11084269/deepBSA.csv)

**Comment by lizhao007** [comment]
你好，VCF中需要删除染色体之外的scaffold，你的文件中是最后这种，
![image](https://user-images.githubusercontent.com/36907006/228752726-ab8005b0-e409-469d-b695-d57787ad93e3.png)
