### ISSUE TITLE
Installing DeepBSA

### ISSUE THREAD

**Issue by cmeesters** [lizhao007/DeepBSA#5]
Hi,

Your software is essentially not versioned, nor is an installer provided. In fact, the combinations of dependencies and specific versions is hard to fulfil. Would you be so kind as to provide a containerized release? Otherwise, administrators like me would constantly have to patch your software or try whether a new release of some dependency breaks your software. 

Thank you very much,
kind regards
Christian Meesters

**Comment by lizhao007** [comment]
At present, all the dependencies of DeepBSA can be automatically installed by running "./requirment.txt", which is quite convenient. Thank you for your suggestion. We will further improve the installation method and only update the necessary dependencies.

**Comment by cmeesters** [comment]
Thank you. The downside of this approach: A user on a multiuser system would have to create a virtual environment to install all dependencies, thereby straining her home directory inodes (many HPC systems allow a limited number of files in $HOME), and has to find a matching Python and R version (compiled with the same compilers, supporting the versions your software requires). And everything is "carved in stone". 

For the time being, this might(!) be a solution. In the long run: Please provide a container, or - even better - put your (future) software in a workflow system (e.g. snakemake, nextflow) for distributed computing, such that dependencies can be resolved individually.

**Comment by slbai01** [comment]
Same suggests, containerized release is a better way.
