### ISSUE TITLE
multithreading

### ISSUE THREAD

**Issue by xizhesun** [lizhao007/DeepBSA#6]
Dear developers,

Does DeepBSA support multithreading? I have not seen a parameter for multithreading in the Linux version.
I have run the Linux version for several days and it only uses one CPU. How long time will it take for an 11 GB VCF file?

All best,
Xizhe

**Comment by lizhao007** [comment]
At present, DeepBSA does not have the function of multithreading. We will consider adding it in the next step. There are two ways to improve the program when the input file is too large. One is preprocessing the data to remove low-quality SNPs with our preprocess function and increasing the filtering threshold of the read number to remove some redundant SNPs. The other is running with a chromosome, which divides the whole genome VCF into chromosome VCFs.

**Comment by xizhesun** [comment]
Thanks for the suggestion. I have run the DeepBSA with parameter "--p1 15 ". So I think split the whole VCF into chromosome VCFs is a good idea.

Best,
Xizhe
