### ISSUE TITLE
smoothing method 

### ISSUE THREAD

**Issue by xizhesun** [lizhao007/DeepBSA#7]
Dear developers,

  Which one do you think is the best smoothing methods  from Tri-kernel-smooth\LOWESS\Moving Average? Why the default smoothing method has been changed from Tri-kernel-smooth (Windows version) to LOWESS (Linux version) ? Have you ever test the demo data for different smoothing method?  For me, only the LOWESS method could successfully get the result.  When I changed to undefault smoothing method, it showed nothing in the result folder.

For example,

> (deepbsa) mals@bioinformatics:~/tools/DeepBSA_linux_v1.4/demo$ python3 ~/tools/DeepBSA_linux_v1.4/bin/main.py --m DL --i test.vcf --s Moving-Average
> 2023-04-10 23:11:31.582990: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
> To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
> 2023-04-10 23:11:31.825574: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
> 2023-04-10 23:11:31.868627: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
> ----------------------------------------------------------------------------------------------------
> file path:test.vcf
> method:DL
> is pretreatment:True
> read number:0
> Chi-square test:True
> Continuity test:True
> smooth method:Moving-Average
> smooth window size:0
> threshold:0
> ----------------------------------------------------------------------------------------------------
> vcf to excel: 107393it [00:01, 66632.01it/s]
> pretreatment: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [01:13<00:00,  7.35s/it]
> pretreatment: 10it [00:02,  4.62it/s]
> /home/data2/mals/anaconda3/envs/deepbsa/lib/python3.7/site-packages/numpy/lib/npyio.py:528: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
>   arr = np.asanyarray(arr)
> pretreatment & files do not exist
> [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
> chrome: 1
> get data
> 2023-04-10 23:12:56.940197: E tensorflow/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
> 2023-04-10 23:12:56.940269: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (bioinformatics): /proc/driver/nvidia/version does not exist
> 2023-04-10 23:12:56.940758: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
> To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
> 6/6 [==============================] - 1s 80ms/step
> get window ratio
> auto window ratio: 0.624672024855963
> Traceback (most recent call last):
>   File "/home/data2/mals/tools/DeepBSA_linux_v1.4/bin/main.py", line 95, in <module>
>     main(args)
>   File "/home/data2/mals/tools/DeepBSA_linux_v1.4/bin/main.py", line 74, in main
>     dl.run()
>   File "/home/data2/mals/tools/DeepBSA_linux_v1.4/bin/functions/Statistic_Methods.py", line 546, in run
>     smooth_for_threshold = np.concatenate((smooth_for_threshold, y), axis=0)
>   File "<__array_function__ internals>", line 6, in concatenate
> ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 0 dimension(s)
> (deepbsa) mals@bioinformatics:~/tools/DeepBSA_linux_v1.4/demo$

All best,
Xizhe

**Comment by lizhao007** [comment]
The three methods have the same function and the same effect. The only difference is that the LOWESS method is a Python package called, and the other two methods are our own code. At present, it is found that only the running time is different, and there is no obvious difference in the results. We are debugging the error of selecting the other two fitting methods in the Linux version. You can run it first with the default method. Thanks for reminding me.

**Comment by xizhesun** [comment]
Thanks for the reply 👍
